DROP TABLE STG.T_STG_TDH_DBASERVICE_QUERY_INFO;
CREATE TABLE STG.T_STG_TDH_DBASERVICE_QUERY_INFO (
    KEY                 STRING,
    SERVERKEY           STRING,
    SQLID               STRING,
    STATUS              STRING,
    STAGEINFO           STRING,
    TASKINFO            STRING,
    USER                STRING,
    DESCRIPTION         STRING,
    metrics_time 		STRING,
    SUBMISSIONTIME      STRING,
    COMPLETIONTIME      STRING,
    WORKFLOWTASKINFO1   STRING,
    SIMILARTY1			STRING,
    WORKFLOWTASKINFO2   STRING,
    SIMILARTY2			STRING,
    WORKFLOWTASKINFO3   STRING,
    SIMILARTY3			STRING,
    MESSAGE             STRING,
    CRAWLMESSAGE        STRING)
STORED BY
  'io.transwarp.hyperdrive.HyperdriveStorageHandler'
WITH SERDEPROPERTIES (
  'hbase.columns.mapping'=':key,f:SERVERKEY,f:SQLID,f:STATUS,f:STAGEINFO,f:TASKINFO,f:USER,f:DESCRIPTION,f:metrics_time,f:SUBMISSIONTIME,f:COMPLETIONTIME,f:WORKFLOWTASKINFO1,f:SIMILARTY1,f:WORKFLOWTASKINFO2,f:SIMILARTY2,f:WORKFLOWTASKINFO3,f:SIMILARTY3,f:MESSAGE,f:CRAWLMESSAGE',
  'serialization.format'='1')
TBLPROPERTIES ('hbase.table.name'='T_STG_TDH_DBASERVICE_QUERY_INFO');




DROP TABLE ODS.T_ODS_TDH_DBASERVICE_QUERY_INFO;
CREATE  TABLE ODS.T_ODS_TDH_DBASERVICE_QUERY_INFO(
  key string DEFAULT NULL,
  serverkey string DEFAULT NULL,
  sqlid string DEFAULT NULL,
  status string DEFAULT NULL,
  stageinfo string DEFAULT NULL,
  taskinfo string DEFAULT NULL,
  user string DEFAULT NULL,
  description string DEFAULT NULL,
  metrics_time string DEFAULT NULL,
  submissiontime string DEFAULT NULL,
  completiontime string DEFAULT NULL,
  workflowtaskinfo1 string DEFAULT NULL,
  similarty1 string DEFAULT NULL,
  workflowtaskinfo2 string DEFAULT NULL,
  similarty2 string DEFAULT NULL,
  workflowtaskinfo3 string DEFAULT NULL,
  similarty3 string DEFAULT NULL,
  message string DEFAULT NULL,
  crawlmessage string DEFAULT NULL
)
PARTITIONED BY RANGE (metrics_time) (
  PARTITION before202201 VALUES LESS THAN ('2022-01-01'),
  PARTITION before202207 VALUES LESS THAN ('2022-07-01'),
  PARTITION before202301 VALUES LESS THAN ('2023-01-01'),
  PARTITION before202307 VALUES LESS THAN ('2023-07-01'),
  PARTITION before202401 VALUES LESS THAN ('2024-01-01'),
  PARTITION before202407 VALUES LESS THAN ('2024-07-01'),
  PARTITION before202501 VALUES LESS THAN ('2025-01-01'),
  PARTITION before202507 VALUES LESS THAN ('2025-07-01'),
  PARTITION before202601 VALUES LESS THAN ('2026-01-01'),
  PARTITION before202607 VALUES LESS THAN ('2026-07-01'),
  PARTITION before202701 VALUES LESS THAN ('2027-01-01'),
  PARTITION before202707 VALUES LESS THAN ('2027-07-01'),
  PARTITION before202801 VALUES LESS THAN ('2028-01-01'),
  PARTITION before202807 VALUES LESS THAN ('2028-07-01'),
  PARTITION before202901 VALUES LESS THAN ('2029-01-01'),
  PARTITION beforemax VALUES LESS THAN (MAXVALUE))
CLUSTERED BY (
  sqlid)
INTO 83 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true');

